- name: Hello World Sample
  hosts: all
  vars:
    ansible_user: administrator
    ansible_password: 1@Welcome@123
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
  
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

